name: PR

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install

    - name: Generate *-state-changes.*
      run: |-
        uv run ./generate-state-changes

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "state-changes"
        path: |
          battleground-state-changes.*
          all-state-changes.*
