name: Scrape latest data

on:
  schedule:
    - cron:  '*/15 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      # NOTE: Needed to push to the repository.
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
    - name: Fetch latest data
      run: |-
        curl "https://static01.nyt.com/elections-assets/pages/data/2024-11-05/results-president.json" | jq . > results.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install

    - name: Generate state-changes
      run: |-
        uv run ./generate-state-changes

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Regenerate state-changes" || exit 0

    - name: Push any changes
      # Pushing once to avoid triggering & canceling multiple actions.
      run: git push
