name: Scrape latest data

on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      # NOTE: Needed to push to the repository.
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
    - name: Fetch latest data
      run: |-
        curl "https://static01.nyt.com/elections-assets/pages/data/2024-11-05/results-president.json" | jq . > results.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
